import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {

  await prisma.savedCollege.deleteMany()

  await prisma.college.deleteMany()

  await prisma.college.createMany({
    data: [
      {
  name: "IIT Madras",
  location: "Chennai",
  state: "Tamil Nadu",
  fees: 240000,
  rating: 4.9,
  description: "India's top engineering institute with strong research and placements.",
 image: "https://th.bing.com/th/id/OIP.2hSVJSK4wXMPCeNcMcAc1gHaE1?w=285&h=186&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹22 LPA",
  highestPackage: "₹1.3 Cr",
  nirfRank: 1,
  establishedYear: 1959,
  ownership: "Government",
  accreditation: "NAAC A++",
  examsAccepted: "JEE Advanced",
  website: "https://www.iitm.ac.in"
},

{
  name: "IIT Delhi",
  location: "New Delhi",
  state: "Delhi",
  fees: 250000,
  rating: 4.9,
  description: "Premier engineering institute known for innovation and entrepreneurship.",
  image: "https://th.bing.com/th/id/OIP.ouwZSmP-zwMw3TrliA15RAHaFj?w=206&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹25 LPA",
  highestPackage: "₹1.5 Cr",
  nirfRank: 2,
  establishedYear: 1961,
  ownership: "Government",
  accreditation: "NAAC A++",
  examsAccepted: "JEE Advanced",
  website: "https://home.iitd.ac.in"
},

{
  name: "IIT Bombay",
  location: "Mumbai",
  state: "Maharashtra",
  fees: 240000,
  rating: 4.8,
  description: "One of India's most prestigious engineering institutions.",
  image: "https://th.bing.com/th/id/OIP.Dc0mClaQWrJdNDLMVPUF_gHaFj?w=166&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹28 LPA",
  highestPackage: "₹1.48 Cr",
  nirfRank: 3,
  establishedYear: 1958,
  ownership: "Government",
  accreditation: "NAAC A++",
  examsAccepted: "JEE Advanced",
  website: "https://www.iitb.ac.in"
},

{
  name: "IIT Kanpur",
  location: "Kanpur",
  state: "Uttar Pradesh",
  fees: 230000,
  rating: 4.8,
  description: "Leading engineering and research institute.",
  image: "https://th.bing.com/th/id/OIP.dq97mmkHXWFAXJp2bhaQLwHaEG?w=336&h=185&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹26 LPA",
  highestPackage: "₹1.2 Cr",
  nirfRank: 4,
  establishedYear: 1959,
  ownership: "Government",
  accreditation: "NAAC A++",
  examsAccepted: "JEE Advanced",
  website: "https://www.iitk.ac.in"
},

{
  name: "IIT Kharagpur",
  location: "Kharagpur",
  state: "West Bengal",
  fees: 225000,
  rating: 4.8,
  description: "Oldest IIT with one of the largest campuses in India.",
  image: "https://th.bing.com/th/id/OIP.pYGjZFiQPaeBpMzuSkggFQHaE8?w=253&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹23 LPA",
  highestPackage: "₹1 Cr",
  nirfRank: 5,
  establishedYear: 1951,
  ownership: "Government",
  accreditation: "NAAC A++",
  examsAccepted: "JEE Advanced",
  website: "https://www.iitkgp.ac.in"
},

{
  name: "IIT Roorkee",
  location: "Roorkee",
  state: "Uttarakhand",
  fees: 220000,
  rating: 4.8,
  description: "Historic engineering institute with excellent placements.",
  image: "https://th.bing.com/th/id/OIP.6E7wB2teJTWggn4siJZQzwHaEO?w=294&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹22 LPA",
  highestPackage: "₹1 Cr",
  nirfRank: 6,
  establishedYear: 1847,
  ownership: "Government",
  accreditation: "NAAC A++",
  examsAccepted: "JEE Advanced",
  website: "https://www.iitr.ac.in"
},

{
  name: "IIT Guwahati",
  location: "Guwahati",
  state: "Assam",
  fees: 220000,
  rating: 4.7,
  description: "Beautiful campus with strong research ecosystem.",
  image: "https://th.bing.com/th/id/OIP.QXIOH8RyXUqO5-CmuXmK3wHaE8?w=243&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹21 LPA",
  highestPackage: "₹1.1 Cr",
  nirfRank: 7,
  establishedYear: 1994,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Advanced",
  website: "https://www.iitg.ac.in"
},

{
  name: "IIT Hyderabad",
  location: "Hyderabad",
  state: "Telangana",
  fees: 230000,
  rating: 4.7,
  description: "Fast-growing IIT with strong startup culture.",
  image: "https://th.bing.com/th/id/OIP.fVHOKCSc-LA0yylr2iAIagHaEO?w=271&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹24 LPA",
  highestPackage: "₹90 LPA",
  nirfRank: 8,
  establishedYear: 2008,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Advanced",
  website: "https://www.iith.ac.in"
},
{
  name: "NIT Trichy",
  location: "Tiruchirappalli",
  state: "Tamil Nadu",
  fees: 180000,
  rating: 4.7,
  description: "Highest ranked NIT in India.",
  image: "https://th.bing.com/th/id/OIP.TTKHJqQ_oT2XicIVJnQyZQHaE8?w=256&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹18 LPA",
  highestPackage: "₹52 LPA",
  nirfRank: 9,
  establishedYear: 1964,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.nitt.edu"
},

{
  name: "NIT Surathkal",
  location: "Mangalore",
  state: "Karnataka",
  fees: 175000,
  rating: 4.6,
  description: "Top NIT known for placements and campus life.",
  image: "https://th.bing.com/th/id/OIP.ilH3Hi48viYBm0AFeOd75QHaDV?w=329&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹16 LPA",
  highestPackage: "₹54 LPA",
  nirfRank: 12,
  establishedYear: 1960,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.nitk.ac.in"
},

{
  name: "NIT Warangal",
  location: "Warangal",
  state: "Telangana",
  fees: 170000,
  rating: 4.6,
  description: "One of India's leading NITs.",
  image: "https://th.bing.com/th/id/OIP.zmOM0bfn2MWzggfbuTTD-gHaEK?w=291&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹15 LPA",
  highestPackage: "₹62 LPA",
  nirfRank: 21,
  establishedYear: 1959,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.nitw.ac.in"
},

{
  name: "NIT Calicut",
  location: "Kozhikode",
  state: "Kerala",
  fees: 170000,
  rating: 4.5,
  description: "Leading engineering institution in South India.",
  image: "https://th.bing.com/th/id/OIP.ujXbSTWO0N1o9c5E5t5YewHaEK?w=308&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹14 LPA",
  highestPackage: "₹50 LPA",
  nirfRank: 25,
  establishedYear: 1961,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://nitc.ac.in"
},

{
  name: "NIT Rourkela",
  location: "Rourkela",
  state: "Odisha",
  fees: 175000,
  rating: 4.5,
  description: "Strong engineering college with research focus.",
  image: "https://th.bing.com/th/id/OIP.PTRWeVL9kQ7Tk0kpfeh7eAHaD0?w=346&h=179&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹14 LPA",
  highestPackage: "₹48 LPA",
  nirfRank: 19,
  establishedYear: 1961,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.nitrkl.ac.in"
},
{
  name: "IIIT Hyderabad",
  location: "Hyderabad",
  state: "Telangana",
  fees: 400000,
  rating: 4.8,
  description: "Premier institute known for Computer Science, AI and research.",
  image: "https://th.bing.com/th/id/OIP.XOcgUfHqmRgK4O6lWqGGrgHaEK?w=272&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹30 LPA",
  highestPackage: "₹1 Cr",
  nirfRank: 47,
  establishedYear: 1998,
  ownership: "Private",
  accreditation: "NAAC A++",
  examsAccepted: "JEE Main",
  website: "https://www.iiit.ac.in"
},

{
  name: "IIIT Bangalore",
  location: "Bengaluru",
  state: "Karnataka",
  fees: 450000,
  rating: 4.7,
  description: "Premier technology institute with excellent placements.",
  image: "https://th.bing.com/th/id/OIP.VVRApAoKM2J7BCdseoytPgHaE8?w=238&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹28 LPA",
  highestPackage: "₹65 LPA",
  nirfRank: 74,
  establishedYear: 1999,
  ownership: "Private",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.iiitb.ac.in"
},

{
  name: "IIIT Delhi",
  location: "New Delhi",
  state: "Delhi",
  fees: 450000,
  rating: 4.7,
  description: "Research-focused institute with strong coding culture.",
  image: "https://th.bing.com/th/id/OIP.HiLx6AHA8WTbvW9pAH8U7QHaEK?w=328&h=184&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹23 LPA",
  highestPackage: "₹82 LPA",
  nirfRank: 85,
  establishedYear: 2008,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.iiitd.ac.in"
},

{
  name: "IIIT Allahabad",
  location: "Prayagraj",
  state: "Uttar Pradesh",
  fees: 190000,
  rating: 4.7,
  description: "One of India's strongest institutes for IT and ECE.",
  image: "https://th.bing.com/th/id/OIP.pIfGm21_sT-XO0akdmgPnwHaE8?w=235&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹22 LPA",
  highestPackage: "₹1.2 Cr",
  nirfRank: 89,
  establishedYear: 1999,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.iiita.ac.in"
},

{
  name: "ABV-IIITM Gwalior",
  location: "Gwalior",
  state: "Madhya Pradesh",
  fees: 180000,
  rating: 4.5,
  description: "Strong institute focused on information technology and management.",
  image: "https://th.bing.com/th/id/OIP.3Ksw0_GQGt_WEa2Hv5ihMQHaEH?w=323&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹16 LPA",
  highestPackage: "₹45 LPA",
  nirfRank: 101,
  establishedYear: 1997,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.iiitm.ac.in"
},

{
  name: "DTU",
  location: "New Delhi",
  state: "Delhi",
  fees: 210000,
  rating: 4.7,
  description: "Top engineering college with strong placements and coding culture.",
  image: "https://th.bing.com/th/id/OIP.3RdB3JXep_WWbnjSGGBmBwHaDq?w=302&h=173&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹18 LPA",
  highestPackage: "₹82 LPA",
  nirfRank: 27,
  establishedYear: 1941,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.dtu.ac.in"
},

{
  name: "NSUT",
  location: "New Delhi",
  state: "Delhi",
  fees: 220000,
  rating: 4.6,
  description: "Highly regarded engineering university with strong tech placements.",
  image: "https://th.bing.com/th/id/OIP.etuWJl-d1kDkfr7dHtvOhgHaEw?w=211&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹16 LPA",
  highestPackage: "₹1 Cr",
  nirfRank: 57,
  establishedYear: 1983,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.nsut.ac.in"
},

{
  name: "IGDTUW",
  location: "New Delhi",
  state: "Delhi",
  fees: 150000,
  rating: 4.6,
  description: "Leading engineering university for women.",
  image: "https://th.bing.com/th/id/OIP.x7n11_TaPUayjClOEch9rAHaE8?w=241&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹14 LPA",
  highestPackage: "₹56 LPA",
  nirfRank: 151,
  establishedYear: 1998,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.igdtuw.ac.in"
},
{
  name: "BITS Pilani",
  location: "Pilani",
  state: "Rajasthan",
  fees: 550000,
  rating: 4.8,
  description: "One of India's most prestigious private engineering institutions.",
  image: "https://th.bing.com/th/id/OIP.JPVWwQ8HjFUp-hvydq7WTwHaEo?w=253&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹22 LPA",
  highestPackage: "₹60 LPA",
  nirfRank: 20,
  establishedYear: 1964,
  ownership: "Private",
  accreditation: "NAAC A++",
  examsAccepted: "BITSAT",
  website: "https://www.bits-pilani.ac.in"
},

{
  name: "VIT Vellore",
  location: "Vellore",
  state: "Tamil Nadu",
  fees: 300000,
  rating: 4.5,
  description: "Popular private university with strong industry connections.",
  image: "https://th.bing.com/th/id/OIP.5BoL2SmuhqkXI20eaz96FgHaE8?w=243&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹10 LPA",
  highestPackage: "₹88 LPA",
  nirfRank: 11,
  establishedYear: 1984,
  ownership: "Private",
  accreditation: "NAAC A++",
  examsAccepted: "VITEEE",
  website: "https://vit.ac.in"
},

{
  name: "Manipal Institute of Technology",
  location: "Manipal",
  state: "Karnataka",
  fees: 420000,
  rating: 4.6,
  description: "Well known private engineering college with global alumni network.",
  image: "https://th.bing.com/th/id/OIP.5pEdL6OD335HdyVdCN7NTwHaFe?w=253&h=187&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹12 LPA",
  highestPackage: "₹54 LPA",
  nirfRank: 14,
  establishedYear: 1957,
  ownership: "Private",
  accreditation: "NAAC A++",
  examsAccepted: "MET",
  website: "https://manipal.edu"
},

{
  name: "SRM Institute of Science and Technology",
  location: "Chennai",
  state: "Tamil Nadu",
  fees: 320000,
  rating: 4.4,
  description: "Large private university with strong placement ecosystem.",
  image: "https://th.bing.com/th/id/OIP.UIfSFPn81v6i03HiiZLJuAHaE8?w=193&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹8 LPA",
  highestPackage: "₹57 LPA",
  nirfRank: 13,
  establishedYear: 1985,
  ownership: "Private",
  accreditation: "NAAC A++",
  examsAccepted: "SRMJEEE",
  website: "https://www.srmist.edu.in"
},

{
  name: "Thapar Institute of Engineering and Technology",
  location: "Patiala",
  state: "Punjab",
  fees: 450000,
  rating: 4.6,
  description: "One of India's leading private engineering institutions.",
  image: "https://th.bing.com/th/id/OIP.czcWlBe2I1rrYuiRY-JO_wHaE7?w=227&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹11 LPA",
  highestPackage: "₹55 LPA",
  nirfRank: 29,
  establishedYear: 1956,
  ownership: "Private",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.thapar.edu"
},

{
  name: "LNMIIT",
  location: "Jaipur",
  state: "Rajasthan",
  fees: 420000,
  rating: 4.5,
  description: "Respected engineering institute known for coding culture.",
  image: "https://th.bing.com/th/id/OIP.OnArSxICyT9fPAeORtJ8PQHaE6?w=269&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹13 LPA",
  highestPackage: "₹50 LPA",
  nirfRank: 151,
  establishedYear: 2002,
  ownership: "Private",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.lnmiit.ac.in"
},

{
  name: "Amrita Vishwa Vidyapeetham",
  location: "Coimbatore",
  state: "Tamil Nadu",
  fees: 350000,
  rating: 4.5,
  description: "Research-focused private university with multiple campuses.",
  image: "https://th.bing.com/th/id/OIP.OhGVp5qDP-Mp9xXUh58lUwHaDz?w=326&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹9 LPA",
  highestPackage: "₹56 LPA",
  nirfRank: 19,
  establishedYear: 2003,
  ownership: "Private",
  accreditation: "NAAC A++",
  examsAccepted: "AEEE",
  website: "https://www.amrita.edu"
},

{
  name: "KIIT",
  location: "Bhubaneswar",
  state: "Odisha",
  fees: 350000,
  rating: 4.4,
  description: "Large private university with strong placement support.",
  image: "https://th.bing.com/th/id/OIP.cTfJPNU1s2odGY38OY2K6gHaEK?w=293&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹8 LPA",
  highestPackage: "₹63 LPA",
  nirfRank: 28,
  establishedYear: 1992,
  ownership: "Private",
  accreditation: "NAAC A++",
  examsAccepted: "KIITEE",
  website: "https://kiit.ac.in"
},
{
  name: "Jadavpur University",
  location: "Kolkata",
  state: "West Bengal",
  fees: 10000,
  rating: 4.8,
  description: "One of India's most respected public engineering universities.",
  image: "https://th.bing.com/th/id/OIP.OqNEFKBfmq6lWQuEWC5GFAHaE8?w=276&h=184&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹12 LPA",
  highestPackage: "₹85 LPA",
  nirfRank: 17,
  establishedYear: 1955,
  ownership: "Government",
  accreditation: "NAAC A+",
  examsAccepted: "WBJEE",
  website: "https://jaduniv.edu.in"
},

{
  name: "COEP Technological University",
  location: "Pune",
  state: "Maharashtra",
  fees: 110000,
  rating: 4.7,
  description: "Historic engineering institution with excellent placements.",
  image: "https://th.bing.com/th/id/OIP.1LBCyCXPFxOKDIEyHtPPkgHaDR?w=275&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹10 LPA",
  highestPackage: "₹50 LPA",
  nirfRank: 73,
  establishedYear: 1854,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "MHT CET",
  website: "https://www.coep.org.in"
},

{
  name: "RV College of Engineering",
  location: "Bengaluru",
  state: "Karnataka",
  fees: 350000,
  rating: 4.6,
  description: "Top private engineering college in Karnataka.",
  image: "https://th.bing.com/th/id/OIP.RYygIvd_ko3gwSrtYfRRtAHaFj?w=216&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹11 LPA",
  highestPackage: "₹62 LPA",
  nirfRank: 99,
  establishedYear: 1963,
  ownership: "Private",
  accreditation: "NAAC A+",
  examsAccepted: "KCET",
  website: "https://rvce.edu.in"
},

{
  name: "PES University",
  location: "Bengaluru",
  state: "Karnataka",
  fees: 450000,
  rating: 4.5,
  description: "Popular university with strong software placements.",
  image: "https://th.bing.com/th/id/OIP.3KfyCx1J1uCESynchDukEAHaE5?w=233&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹9 LPA",
  highestPackage: "₹65 LPA",
  nirfRank: 101,
  establishedYear: 1972,
  ownership: "Private",
  accreditation: "NAAC A+",
  examsAccepted: "PESSAT",
  website: "https://www.pes.edu"
},

{
  name: "MS Ramaiah Institute of Technology",
  location: "Bengaluru",
  state: "Karnataka",
  fees: 320000,
  rating: 4.5,
  description: "Well known engineering college with strong industry ties.",
  image: "https://th.bing.com/th/id/OIP.is_jM3sRscAhsy56WnsYwwHaBn?w=324&h=76&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹8 LPA",
  highestPackage: "₹50 LPA",
  nirfRank: 78,
  establishedYear: 1962,
  ownership: "Private",
  accreditation: "NAAC A+",
  examsAccepted: "KCET",
  website: "https://www.msrit.edu"
},

{
  name: "DAIICT",
  location: "Gandhinagar",
  state: "Gujarat",
  fees: 300000,
  rating: 4.6,
  description: "Specialized institute for ICT and Computer Science.",
  image: "https://th.bing.com/th/id/OIP.jiJNAsB3Hnc8woTEIM_C4gAAAA?w=230&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹15 LPA",
  highestPackage: "₹55 LPA",
  nirfRank: 151,
  establishedYear: 2001,
  ownership: "Private",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://www.daiict.ac.in"
},

{
  name: "Nirma University",
  location: "Ahmedabad",
  state: "Gujarat",
  fees: 280000,
  rating: 4.4,
  description: "Leading private university with strong engineering programs.",
  image: "https://th.bing.com/th/id/OIP.XWx4h3Jg-8Oy5mLmSPm1FwHaDF?w=348&h=145&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹8 LPA",
  highestPackage: "₹44 LPA",
  nirfRank: 101,
  establishedYear: 2003,
  ownership: "Private",
  accreditation: "NAAC A+",
  examsAccepted: "JEE Main",
  website: "https://nirmauni.ac.in"
},

{
  name: "PEC Chandigarh",
  location: "Chandigarh",
  state: "Chandigarh",
  fees: 170000,
  rating: 4.5,
  description: "Historic engineering college with strong alumni network.",
  image: "https://th.bing.com/th/id/OIP.AtNMSDF_O9ndrbicoF0UxAHaFj?w=231&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹12 LPA",
  highestPackage: "₹52 LPA",
  nirfRank: 87,
  establishedYear: 1921,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://pec.ac.in"
},
{
  name: "NIT Jalandhar",
  location: "Jalandhar",
  state: "Punjab",
  fees: 165000,
  rating: 4.4,
  description: "Established NIT with strong engineering programs.",
  image: "https://th.bing.com/th/id/OIP.U1MOwD1zXwEOrnKdNXweAAHaEN?w=259&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹10 LPA",
  highestPackage: "₹45 LPA",
  nirfRank: 46,
  establishedYear: 1987,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.nitj.ac.in"
},

{
  name: "NIT Kurukshetra",
  location: "Kurukshetra",
  state: "Haryana",
  fees: 165000,
  rating: 4.4,
  description: "Leading engineering institution in North India.",
  image: "https://th.bing.com/th/id/OIP.OR9WaemFvGqyqpTQEe1QewHaE8?w=268&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹10 LPA",
  highestPackage: "₹42 LPA",
  nirfRank: 58,
  establishedYear: 1963,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://nitkkr.ac.in"
},

{
  name: "NIT Durgapur",
  location: "Durgapur",
  state: "West Bengal",
  fees: 160000,
  rating: 4.4,
  description: "Well-known NIT with strong placement record.",
  image: "https://th.bing.com/th/id/OIP._zhM_WAnaCnfsSeNfmQWAAHaDt?w=323&h=174&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹11 LPA",
  highestPackage: "₹51 LPA",
  nirfRank: 44,
  establishedYear: 1960,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://nitdgp.ac.in"
},

{
  name: "BIT Mesra",
  location: "Ranchi",
  state: "Jharkhand",
  fees: 280000,
  rating: 4.5,
  description: "Historic engineering institute with strong alumni network.",
  image: "https://th.bing.com/th/id/OIP.ntuC2dZCCpuEBCj4JnR4wwHaDZ?w=292&h=160&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹9 LPA",
  highestPackage: "₹52 LPA",
  nirfRank: 53,
  establishedYear: 1955,
  ownership: "Private",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.bitmesra.ac.in"
},

{
  name: "IIEST Shibpur",
  location: "Howrah",
  state: "West Bengal",
  fees: 140000,
  rating: 4.5,
  description: "Institute of national importance with strong engineering heritage.",
  image: "https://th.bing.com/th/id/OIP.smP0I_IdOv4IVvCQRGwi4gHaEK?w=328&h=184&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹10 LPA",
  highestPackage: "₹40 LPA",
  nirfRank: 49,
  establishedYear: 1856,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.iiests.ac.in"
},

{
  name: "IIIT Lucknow",
  location: "Lucknow",
  state: "Uttar Pradesh",
  fees: 220000,
  rating: 4.6,
  description: "Fast-growing IIIT known for coding culture and placements.",
  image: "https://th.bing.com/th/id/OIP.Cur-_PJewljcXXgftfL80wHaDt?w=341&h=175&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹18 LPA",
  highestPackage: "₹62 LPA",
  nirfRank: 87,
  establishedYear: 2015,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://iiitl.ac.in"
},

{
  name: "IIIT Pune",
  location: "Pune",
  state: "Maharashtra",
  fees: 220000,
  rating: 4.4,
  description: "Emerging IIIT with strong focus on technology education.",
  image: "https://th.bing.com/th/id/OIP.k1Ja9NdX7ElZkyv4QSUhIQHaE9?w=224&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹12 LPA",
  highestPackage: "₹35 LPA",
  nirfRank: 151,
  establishedYear: 2016,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.iiitp.ac.in"
},

{
  name: "IIIT Sri City",
  location: "Sri City",
  state: "Andhra Pradesh",
  fees: 220000,
  rating: 4.5,
  description: "Modern IIIT with strong industry exposure.",
  image: "https://th.bing.com/th/id/OIP.t1bEEGI3iVYarjbWbLGOAgHaE8?w=255&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  avgPackage: "₹14 LPA",
  highestPackage: "₹40 LPA",
  nirfRank: 151,
  establishedYear: 2013,
  ownership: "Government",
  accreditation: "NAAC A",
  examsAccepted: "JEE Main",
  website: "https://www.iiits.ac.in"
}
    ],
  });

  console.log("Seed completed");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());