export type FallbackCollege = {
  id: string;
  name: string;
  location: string;
  state: string | null;
  fees: number;
  avgPackage: string;
  highestPackage: string | null;
  nirfRank: number;
  rating: number;
  ownership: string | null;
  accreditation: string | null;
  examsAccepted: string | null;
  website: string | null;
  description: string;
  establishedYear: number | null;
  image: string;
};

export const fallbackColleges: FallbackCollege[] = [
  {
    id: "fallback-iit-madras",
    name: "IIT Madras",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 240000,
    avgPackage: "₹22 LPA",
    highestPackage: "₹1.3 Cr",
    nirfRank: 1,
    rating: 4.9,
    ownership: "Government",
    accreditation: "NAAC A++",
    examsAccepted: "JEE Advanced",
    website: "https://www.iitm.ac.in",
    description: "India's top engineering institute with strong research and placements.",
    establishedYear: 1959,
    image: "https://th.bing.com/th/id/OIP.2hSVJSK4wXMPCeNcMcAc1gHaE1?w=285&h=186&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-iit-delhi",
    name: "IIT Delhi",
    location: "New Delhi",
    state: "Delhi",
    fees: 250000,
    avgPackage: "₹25 LPA",
    highestPackage: "₹1.5 Cr",
    nirfRank: 2,
    rating: 4.9,
    ownership: "Government",
    accreditation: "NAAC A++",
    examsAccepted: "JEE Advanced",
    website: "https://home.iitd.ac.in",
    description: "Premier engineering institute known for innovation and entrepreneurship.",
    establishedYear: 1961,
    image: "https://th.bing.com/th/id/OIP.ouwZSmP-zwMw3TrliA15RAHaFj?w=206&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-iit-bombay",
    name: "IIT Bombay",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 240000,
    avgPackage: "₹28 LPA",
    highestPackage: "₹1.48 Cr",
    nirfRank: 3,
    rating: 4.8,
    ownership: "Government",
    accreditation: "NAAC A++",
    examsAccepted: "JEE Advanced",
    website: "https://www.iitb.ac.in",
    description: "One of India's most prestigious engineering institutions.",
    establishedYear: 1958,
    image: "https://th.bing.com/th/id/OIP.Dc0mClaQWrJdNDLMVPUF_gHaFj?w=166&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-iit-kanpur",
    name: "IIT Kanpur",
    location: "Kanpur",
    state: "Uttar Pradesh",
    fees: 230000,
    avgPackage: "₹26 LPA",
    highestPackage: "₹1.2 Cr",
    nirfRank: 4,
    rating: 4.8,
    ownership: "Government",
    accreditation: "NAAC A++",
    examsAccepted: "JEE Advanced",
    website: "https://www.iitk.ac.in",
    description: "Leading engineering and research institute.",
    establishedYear: 1959,
    image: "https://th.bing.com/th/id/OIP.dq97mmkHXWFAXJp2bhaQLwHaEG?w=336&h=185&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-nit-trichy",
    name: "NIT Trichy",
    location: "Tiruchirappalli",
    state: "Tamil Nadu",
    fees: 180000,
    avgPackage: "₹18 LPA",
    highestPackage: "₹52 LPA",
    nirfRank: 9,
    rating: 4.7,
    ownership: "Government",
    accreditation: "NAAC A+",
    examsAccepted: "JEE Main",
    website: "https://www.nitt.edu",
    description: "Highest ranked NIT in India.",
    establishedYear: 1964,
    image: "https://th.bing.com/th/id/OIP.TTKHJqQ_oT2XicIVJnQyZQHaE8?w=256&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-nit-surathkal",
    name: "NIT Surathkal",
    location: "Mangalore",
    state: "Karnataka",
    fees: 175000,
    avgPackage: "₹16 LPA",
    highestPackage: "₹54 LPA",
    nirfRank: 12,
    rating: 4.6,
    ownership: "Government",
    accreditation: "NAAC A+",
    examsAccepted: "JEE Main",
    website: "https://www.nitk.ac.in",
    description: "Top NIT known for placements and campus life.",
    establishedYear: 1960,
    image: "https://th.bing.com/th/id/OIP.ilH3Hi48viYBm0AFeOd75QHaDV?w=329&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-nit-warangal",
    name: "NIT Warangal",
    location: "Warangal",
    state: "Telangana",
    fees: 170000,
    avgPackage: "₹15 LPA",
    highestPackage: "₹62 LPA",
    nirfRank: 21,
    rating: 4.6,
    ownership: "Government",
    accreditation: "NAAC A+",
    examsAccepted: "JEE Main",
    website: "https://www.nitw.ac.in",
    description: "One of India's leading NITs.",
    establishedYear: 1959,
    image: "https://th.bing.com/th/id/OIP.zmOM0bfn2MWzggfbuTTD-gHaEK?w=291&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-dtu",
    name: "DTU",
    location: "New Delhi",
    state: "Delhi",
    fees: 210000,
    avgPackage: "₹18 LPA",
    highestPackage: "₹82 LPA",
    nirfRank: 27,
    rating: 4.7,
    ownership: "Government",
    accreditation: "NAAC A+",
    examsAccepted: "JEE Main",
    website: "https://www.dtu.ac.in",
    description: "Top engineering college with strong placements and coding culture.",
    establishedYear: 1941,
    image: "https://th.bing.com/th/id/OIP.3RdB3JXep_WWbnjSGGBmBwHaDq?w=302&h=173&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-iiit-hyderabad",
    name: "IIIT Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    fees: 400000,
    avgPackage: "₹30 LPA",
    highestPackage: "₹1 Cr",
    nirfRank: 47,
    rating: 4.8,
    ownership: "Private",
    accreditation: "NAAC A++",
    examsAccepted: "JEE Main",
    website: "https://www.iiit.ac.in",
    description: "Premier institute known for Computer Science, AI and research.",
    establishedYear: 1998,
    image: "https://th.bing.com/th/id/OIP.XOcgUfHqmRgK4O6lWqGGrgHaEK?w=272&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-iiit-allahabad",
    name: "IIIT Allahabad",
    location: "Prayagraj",
    state: "Uttar Pradesh",
    fees: 190000,
    avgPackage: "₹22 LPA",
    highestPackage: "₹1.2 Cr",
    nirfRank: 89,
    rating: 4.7,
    ownership: "Government",
    accreditation: "NAAC A",
    examsAccepted: "JEE Main",
    website: "https://www.iiita.ac.in",
    description: "One of India's strongest institutes for IT and ECE.",
    establishedYear: 1999,
    image: "https://th.bing.com/th/id/OIP.pIfGm21_sT-XO0akdmgPnwHaE8?w=235&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
  {
    id: "fallback-iiit-lucknow",
    name: "IIIT Lucknow",
    location: "Lucknow",
    state: "Uttar Pradesh",
    fees: 220000,
    avgPackage: "₹18 LPA",
    highestPackage: "₹62 LPA",
    nirfRank: 87,
    rating: 4.6,
    ownership: "Government",
    accreditation: "NAAC A",
    examsAccepted: "JEE Main",
    website: "https://iiitl.ac.in",
    description: "Fast-growing IIIT known for coding culture and placements.",
    establishedYear: 2015,
    image: "https://th.bing.com/th/id/OIP.Cur-_PJewljcXXgftfL80wHaDt?w=341&h=175&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
  },
];
